name: Generate Snake Animation
on:
  schedule:
    - cron: "0 0 * * *"  # Atualiza diariamente
  workflow_dispatch:      # Permite execução manual
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: "output/github-contribution-grid-snake.svg"
      - run: git config --global user.name "GitHub Actions"
      - run: git config --global user.email "actions@github.com"
      - run: git add -A && git commit -m "Update snake animation" && git push
