name: Generate Snake
on:
  schedule:
    - cron: '0 0 * * *'  # Executa diariamente
  workflow_dispatch:      # Permite executar manualmente

permissions:
  contents: write        # Permissão para fazer push

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Baixa todo o histórico

      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: "output/snake.svg"  # Nome mais simples

      - name: Force Update SVG
        run: |
          mkdir -p output  # Cria a pasta se não existir
          date > output/snake.svg  # Garante que o arquivo será atualizado

      - name: Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add output/
          git commit -m "Update snake" || echo "Sem alterações"
          git pull --rebase origin main
          git push origin main
